#!/bin/sh
yad --title="Conky" --width=205 --window-icon="/usr/share/miyolinux/miyolinux.png" --text-align=center --center --buttons-layout="center" --text="
Turn the Conky On or Off.
" \
--button="On":"conky" \
--button="Off":"killall conky" \
--button="Close" \
