#!/bin/sh
yad --title="Touchpad Controls" --width=370 --window-icon="/usr/share/miyolinux/miyolinux.png" --center --buttons-layout="center" --text-align=center --text="
HINT:  Your touchpad must already be ON
 and active before selecting Off While Typing.
" \
--button="On":"synclient TouchpadOff=0" \
--button="Off":"synclient TouchpadOff=1" \
--button="Off While Typing":"syndaemon -i 2.0 -d" \
--button="Close" \